POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "jim",
    "password": "jim"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "jim",
    "password": "jim"
}
###
POST http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExNTIzZmU0YWU2N2VmMWRkZDY4OTIiLCJpYXQiOjE2Nzg4NjE4ODF9.ILtB6s2PbMSbOr3BoRBMuA7uL3eXWuSHmVVvAQqNq0w
Content-Type: application/json

{
    "title":"time to rob",
    "description":"rob stark",
    "url":"hbo.com",
    "status":"LEARNING"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExNjM1NjdhOWJkMjE4ZGNkYzZkOTYiLCJpYXQiOjE2Nzg4NjI2MzR9.61uTlB2KQc8ZcZ_gbXY7-C5pvZexl7vvxeuHJvMnLQ0

###
PUT http://localhost:5000/api/posts/641164113e1b55d1c681a666
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExNjM1NjdhOWJkMjE4ZGNkYzZkOTYiLCJpYXQiOjE2Nzg4NjI2MzR9.61uTlB2KQc8ZcZ_gbXY7-C5pvZexl7vvxeuHJvMnLQ0
Content-Type: application/json

{
    "title":"time to do sth diff",
    "description":"take her to the cinema",
    "url":"CGVcinema.com",
    "status":"TO LEARN"
}

###
DELETE http://localhost:5000/api/posts/641164113e1b55d1c681a666
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDExNjM1NjdhOWJkMjE4ZGNkYzZkOTYiLCJpYXQiOjE2Nzg4NjI2MzR9.61uTlB2KQc8ZcZ_gbXY7-C5pvZexl7vvxeuHJvMnLQ0
